### ISSUE TITLE
Spotify plugin seems to be broken.

### ISSUE THREAD

**Issue by pfischi** [SoCo/SoCo#206]
Currently i'am trying to implement the Spotify plugin without success.
So that's what i've done so far:

spotify = Spotify(self.soco)
spotify.add_track_to_queue(SpotifyTrack('spotify:track:7kCrYUDtWsPldohOKPTKPL'))

A track with the full sonos-uri is added to the list, but this track is not playable from a sonos IOS or Android app. The program rejects the play action with 'a file not found exception'. When i add the '?sid=9&flags=32' to the track uri ( i do it in the uri getter of the SpotifyTrack class) the track is queued and playable. But the metaddata is still missing.

Stefan

**Comment by ghosthugger** [comment]
I tried to use the Spotify plugin but the SpotifyTrack class is missing the method to_elements() and the property resources.

Looks like they have been renamed in other parts of the codebase, but forgotten here

**Comment by KennethNielsen** [comment]
Hallo @pfischi and @ghosthugger 

Thanks for the reports. Its unfortunate that this plugin seems to have been forgotten in some of the refractoring. However, we (or rather @lawrenceakka) is in the process of working on some new code, that should work as a universal music service plugin, rather than having to implement each of the music services on their own. Obviously, we would much rather be working on this universal approach rather than fixing bugs in code that will likely be deprecated in the near future.

With a little patience, we should hopefully have a new and working Spotify plugin again. So unless you feel strongly about it, or are willing to work on it yourselves, I think we should regards this as a won't-fix.

I hope this is ok. Otherwise let me know in the comments.

**Comment by KennethNielsen** [comment]
We should leave this issue open until the new code arrives.

**Comment by lawrenceakka** [comment]
See [this Gist](<https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2>)
