### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by mahescho** [SoCo/SoCo#279]
Hi,

all my speakers use SSL on port 1433, so none gets detected as SoCo only uses port 1400 and no SSL.
```
nmap -sS -n 192.168.100.41

Starting Nmap 6.40 ( http://nmap.org ) at 2015-01-18 14:39 CET
Nmap scan report for 192.168.100.41
Host is up (0.00079s latency).
Not shown: 999 closed ports
PORT     STATE SERVICE
1443/tcp open  ies-lm
MAC Address: B8:E9:37:3C:CC:62 (Sonos)

Nmap done: 1 IP address (1 host up) scanned in 61.60 seconds
```
```
curl --insecure https://192.168.100.41:1443/xml/device_description.xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
    <friendlyName>192.168.100.41 - Sonos PLAY:3</friendlyName>
    <manufacturer>Sonos, Inc.</manufacturer>
    <manufacturerURL>http://www.sonos.com</manufacturerURL>
    <modelNumber>S3</modelNumber>
    <modelDescription>Sonos PLAY:3</modelDescription>
    <modelName>Sonos PLAY:3</modelName>
    <modelURL>http://www.sonos.com/products/zoneplayers/S3</modelURL>
    <softwareVersion>28.1-83040</softwareVersion>
    <hardwareVersion>1.8.1.3-2</hardwareVersion>
....
....
```
Matthias

**Comment by KennethNielsen** [comment]
Did you set them up somehow to use SSL?

**Comment by mahescho** [comment]
No - at least not intentionally. Is there a way to do so?

**Comment by lawrenceakka** [comment]
What this tells me is that (1) your Sonos device is not revealing all its open ports to nmap (not unusual!), and (2) that the device_description page is available on port 1443 via https (also not unusual)

In fact, my system responds exactly the same way.

What it doesn't tell me is whether the device description page is available also via http on port 1400 (mine is), and what happens when you use the discovery function.

Please can you try:
```python
from soco import discover
print discover()
```
and let us know what the output is.

**Comment by lawrenceakka** [comment]
I'm going to close this for now. Please reopen if you can provide any more information

**Comment by phyamane** [comment]
I am running in to the same issue. When I run discover() my output is:
set([SoCo("192.168.1.12"), SoCo("192.168.1.13")])
