### ISSUE TITLE
@only_on_master causes exception when calling play_uri

### ISSUE THREAD

**Issue by ArjanM83** [SoCo/SoCo#321]
What I'm doing:
1. Joining a stereo pair Play 5's (zone 1) with a stereo pair of Play 1's (zone 2) with one Play 5 (zone 3).
2. Playing a TTS message in this group.
3. Unjoining zone 2 from the group
4. Unjoining zone 3 from the group
5. Then resuming playing music on zone 3

play_uri then often (50% of the time) raises an exception: only_on_master

My thoughts:
Unjoining takes time. Directly calling play_uri raises the exception.
It seems SoCo thinks the zone is still in a group.
Waiting 10s after unjoining does solve this, but this takes too long.
Removing @only_on_master from play_uri also solves the issue.
After a few seconds the zone starts playing, without exception.

Maybe the @only_on_master is not required for this and other functions?
I've removed this line in my local version, which solves the issue for me.

**Comment by KennethNielsen** [comment]
Hallo @ArjanM83 

The only_on_master decorator was added last release, to take care of the problem, that performing certain tasks on not-master zones in a group, will either produce difficult to decipher errors or weird and inconsistent behavior, so we would like to keep it ;)

In any case, I do not think the problem is this decorator. I think the problem is that SoCo does not know that the zone has been unjoined from the group. I think it should be possible to fix this by updating the group topology information after the unjoin operation. I will look into it.

**Comment by KennethNielsen** [comment]
Hmm. It seems to be not quite so simple, it is also tied in with a caching issue. I will look at it some more.

**Comment by KennethNielsen** [comment]
I think I got it now. @ArjanM83 do you have the possibility to test out this branch: https://github.com/KennethNielsen/SoCo/tree/issue_321_unjoin_not_reflected_in_is_coordinator ?

**Comment by ArjanM83** [comment]
Hi Kenneth,

Thank you for looking into this.
I will be able to test this during the weekend.

I will get back to you in a couple of days.

**Comment by KennethNielsen** [comment]
I almost forgot to mention it. When dealing with zones in a group, the easiest way to find the coordinator, to find the zone to send commands to, is with ``myzone.group.coordinator``.

**Comment by ArjanM83** [comment]
Hi Kenneth,

I've tested the branch. I've been joining and unjoining zones, and playing music on them, tens of times.

The issue is solved now. Thank you for your work.

**Comment by KennethNielsen** [comment]
No problem, thanks for reporting it.
