### ISSUE TITLE
Shortcut for DidlObject.resources[0].uri

### ISSUE THREAD

**Issue by ghcs27** [SoCo/SoCo#472]
I have noticed that I use `DidlObject.resources[0].uri` quite often and it is also present in the SoCo code multiple times. Hardcoding the index `[0]` in so many places does not seem very good practice to me, I would propose adding a `uri` property to DidlObject which returns `resources[0].uri`:

If, for instance, we were to encounter metadata with two `<res>` tags of which only the second one contains the URI, code at many different places would have to be updated. With an adaptable property, this wouldn't be a problem.

What do you think?

**Comment by KennethNielsen** [comment]
Sounds like a good idea. Do you want to write it up? If you do, make sure there is no name clash for uri.

**Comment by ghcs27** [comment]
While writing the property, I came across the question: Should it have a setter?
Setting the uri of a DidlObject which does not yet have a resource object would create a new `DidlResource` with a generic protocol info.

**Comment by ghcs27** [comment]
The line `DidlResource(uri=[uri], protocol_info="[uri_prefix]:*:*:*")` is quite frequent. I reckon that `[uri_prefix]:*:*:*` should be the default protocol info, which would make a setter for `DidlObject.uri` simpler.

**Comment by KennethNielsen** [comment]
I think, let's see if a need arises for a setter. At least that is a lot more rare, so maybe it is ok if people will have to manipulate the `.resources` directly for that.

**Comment by ghcs27** [comment]
Well, I just had a look at my own code:
```python
res = [DidlResource(uri=uri, protocol_info="x-rincon-playlist:*:*:*")]
item = DidlObject(resources=res, title=title, parent_id='', item_id='')
```
isn't as intuitive or readable as
```python
item = DidlObject(title=title, parent_id='', item_id='')
item.uri = uri
```
or even better
```python
item = DidlObject(title=title, parent_id='', item_id='', uri=uri)
```
The first code block even crops up in the SoCo code: see add_uri_to_queue() and create_sonos_playlist.

**Comment by ghcs27** [comment]
@KennethNielsen Drafts of my changes are at

- [`ghcs27:didl_object_uri`](https://github.com/ghcs27/SoCo/tree/didl_object_uri) without setter or protocol info default
- [`ghcs27:didl_object_uri_with_setter`](https://github.com/ghcs27/SoCo/tree/didl_object_uri) including setter and protocol info default

Can you please take a look at them?

Another question: Would it be feasible to change the signature of the DidlObject constructor (e.g. to include an optional uri parameter)?

**Comment by KennethNielsen** [comment]
Hi @ghcs27 

Regarding the setter, thanks for doing the research regarding use in the soco code base. I see your point about readability, but I have a concern about consistency. The point is, that the implementation of the data structures follows the DIDL-Lite specification fairly closely, and in this the (binary) resources attached to an object is defined internally be separate resource objects. Staying close to the spec has value if it is ever updated or similar. Of course we can (and probably should) add stuff on top for convenience, but we should be careful (I think) not to change the way we think about the data structures. An object does not, according to the spec and the implementation, have a single well defined uri. So the question is, how do we resolve this with the desire for convenience? I have given this some though and these are my opinions (feel free to disagree):

**Regarding the getter:** I like the idea of having a getter for the uri. How do we resolve the issue that there is principle can be more than one. We could return a list of uris always, but ``myitem.uris[0] is but-ugly, so I think is a reasonable compromise to have just the uri getter, but document it **very clearly** in its doc string, that it returns the uri of the first resource.

**Regarding the setter:** Here I am a lot more in doubt. I am a strong proponent of Pythons focus on readability and I believe that it should, to a certain extent, govern implementation. But readability (at least in my view) is not just about having the shorter, more convenient, form. It is also about accurately communicating the concepts of the implementation, that the user needs to know about[1]. So I'm really worried, that making a simple property setter would hide to much. E.g. in the case of more resources, which one would be set (ok, that could be documented). What if there are no resources? How certain are we that the `protocol_info="x-rincon-playlist:*:*:*"` is the sensible choice?[2] I find it difficult to imagine this being solved nicely and elegantly with a setter or a change to the initializer (__init__)[3], because in both cases the presence or a single uri argument would betray the implementation.

What I could imagine is having a proper ``set_uri`` method. In that it would be possible, to accurately communicate all the nuances with a interface along the lines of ``set_uri(uri, resource=0, default_protocol_info="x-rincon-playlist:*:*:*")`` where the docstring would explain that ``default_protocol_info`` is only used when there are no resources. The question that then arises is what about symmetry? Having a property getter and a set method is not nice. Maybe they should both be methods then. Note, that while Python allows us to implement properties, and that they are nice to use, there isn't a rule that we should use them, when there isn't a simple way to implement them.

What do you think about this? I would like to hear your thoughts, and then we can figure out which PR to run with.

[1] For an example of this I would refer to something like matplotlibs object oriented interface.
[2] And of course as always, it is always good to think thoroughly about adding stuff to the soco API because, once it is there, it is sooo much trouble to remove or change if it turned out to not be right.
[3] which, to answer your question, yes, I believe, would be possible

**Comment by ghcs27** [comment]
Wow, that's a lot of thought you put into my suggestion. I see that there are lots of things to take care of from a code management perspective: Thank you for the insightful explaination!
I agree that communicating the concepts of the Sonos interface is important and I can see how a single uri setter would betray the implementation. Therefore, I will open a PR for the getter only version with added documentation. If I have an idea for a conclusive implementation of the setter, I might raise this issue again, but for now the getter is actually enough.
