### ISSUE TITLE
how to add a song from spotify to a playlist

### ISSUE THREAD

**Issue by samaelv95** [SoCo/SoCo#473]
Hello, i'm trying to add a song from spotify to a playlist of sonos, when i pass a queueable item and a playlist to the function add_item_to_sonos_playlist it does add to the playlist but the image and the title doesn't show up in the app of sonos. so my question is, there is a form to make a queueable item from the url of a spotify song? i can get the url of this form x-sonos-spotify:spotify:track:3EmmCZoqpWOTY1g2GBwJoR?sid=9&flags=8224&sn=3
thanks for your help

**Comment by KennethNielsen** [comment]
@samaelv95 It isn't possible to add a Spotify song using only a uri, because the Spotify content is hidden behind authentication. To get queue-able Spotify items, you should use the music services code (http://docs.python-soco.com/en/latest/api/soco.music_services.music_service.html). Unfortunately, there was recently a change if how many of the music services handle the authentication, which means that right it doesn't work :(

**Comment by KennethNielsen** [comment]
With no additional information I'll consider this closed. Feel free to re-open if you think the issue wa not resolved.
