### ISSUE TITLE
snapshot code confusion over self.playlist_position

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#475]
While reading through the snapshot code I stumbled on this:

```python
            if self.is_playing_queue and self.playlist_position > 0:
                # was playing from playlist

                if self.playlist_position is not None:
```

which I saw as a potential Python 3 bug. Since, if `self.playlist_position` can be `None`, `self.playlist_position > 0` will fail on Python 3 (unorderable types), while it was allowed under Python2.

When you then look at how the value is retrieved it goes:

```python
                position = track_info['playlist_position']
                if position != "":
                    # save as integer
                    self.playlist_position = int(position)
```

So it is indeed possible, that the property will not be changed away from init value of None.

Maybe the order of the checks in the first code snippet should be changed. This should be investigated.

**Comment by DPH** [comment]
Can have a look next week.
Cheers David

**Comment by KennethNielsen** [comment]
@DPH Thanks

**Comment by robwebset** [comment]
Seems to make sense - I have to confess that I don't think I use this class any more - but sounds like others are finding it useful, so at least it is getting used!

**Comment by DPH** [comment]
Have looked into this.
@KennethNielsen the test does technically fail on Python 3, but I find I have been using this code live for many months on Python 3 and it has not caused me any problems. 

However, we should make it right so have made a pull request that fixes the problem and adds documentation that this is a use once class. I have initialised self.playlist_position value as 0 as this makes more sense and solves the problem. Have had this code running since the weekend. 

Have made the changes in DPH/Soco branch: snap_upd.
When I try to create a pull request it lists loads of other changes as well as this 2 line change!
Welcome advice on what I have done wrong / need to do to make a pull request.

Regards Daivd

**Comment by KennethNielsen** [comment]
@DPH Thanks for the research. I think maybe you need to rebase you branch. When you look at the history, how old is the last change before your changes? I can easily help you with it, but that would be easier e.g. IRC. I don't know if we share a time zone suitable for that. I'm UTC+1.

**Comment by KennethNielsen** [comment]
@DPH did you need some help fixing the git?

**Comment by DPH** [comment]
Yes please. Sorry have been away for a few days.
Am around tomorrow if you are.

Regards David

**Comment by KennethNielsen** [comment]
Ah great. We still have the #soco channel on freenode. If you log on there tomorrow when it suits you, then I will see how I can make it fit. My job is a kind of support, so it is a little difficult for me to predict when I can rip a little time out of the schedule. I know I have an appointment at 9 GMT and probably 30-45 min forward, but other that that, it's difficult to say.

**Comment by DPH** [comment]
Thanks - am very flexible tomorrow so can fit in with you.
Assuming you are in Copenhagen you are one hour ahead of the UK.
Will log in soon after 9 UK time (10 for you), and will be around - so
shout when it works.

Cheers David

**Comment by DPH** [comment]
Created new pull request #489 after fixing my git repository!
