### ISSUE TITLE
Error calling discover caused by log statement

### ISSUE THREAD

**Issue by mkoestner** [SoCo/SoCo#492]
I get the following error calling soco.discover():

> Traceback (most recent call last):
  File "main.py", line 142, in <module>
    actionSonos.connect()
  File "D:\WebstormProjects\playercontrol\playercontrol\action\sonosproxy.py", line 23, in connect
    zone_list = list(soco.discover())
  File "D:\dev\Python27\lib\site-packages\soco\discovery.py", line 123, in discover
    list(s.getsockname()[0] for s in _sockets))
  File "D:\dev\Python27\lib\site-packages\soco\discovery.py", line 123, in <genexpr>
    list(s.getsockname()[0] for s in _sockets))
  File "D:\dev\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10022] Ein ung³ltiges Argument wurde angegeben

I traced that error back to line 122 of discovery.py where s.getsockname() causes the error. Commenting out the two logging lines solves the problem.

**Comment by DPH** [comment]
Hi @mkoestner,
well discovered - I believe this occurs on Windows only. 
It was identified some time ago and has been fixed in the latest code and will be included in the next release. If you want to download the latest from this git repository you should find it is now OK. 
Let us know if you have any more problems

Regards David

**Comment by mkoestner** [comment]
Ah, great thanks. That was quick.

Fixed with 1ee005a8931e6c18d803ab4d589e6f45544ddb1c
