### ISSUE TITLE
stream local PC audio

### ISSUE THREAD

**Issue by DeveloperACE** [SoCo/SoCo#531]
I have tried searching this repository and the google groups page for this project and still can't seem to find the answer.

I want to try and use my SONOS speaker as a PC speaker and have already tried https://github.com/stephen/airsonos, however the delay for watching things like youtube videos was far too high for me.

I have the capability to connect my PC to my Sonos via ethernet cable and I was wondering if there was any way I could use that in tandem with your SoCo library to somehow output all my computer's audio to my SONOS. I didn't see anything besides playing a specific sound file or getting a remote stream and was wondering if there is either existing functionality for broadcasting local PC audio over a wired connection or if something like this could be added to SoCo.

**Comment by KennethNielsen** [comment]
Hi @DeveloperACE 

If the delay with airsonos is constant, then why not just delay the video correspondingly (VLC can do that)? But maybe you want to do other things like video games as well, and then that wont work.

The reason I ask is that it is a difficult problem. Sonos can **only** play streams available on the network. So how do you get all sound from your computer available as a streaming channel (without delay). I think the only realistic answer is, that you need somehow, to interact directly with the sound system. I'm a Linux person, so there I have several times advised people to look into asking Pulse Audio or ALSA (the sound system on Linux) to stream directly, since (I think) both of these have a source-sink kind of design, where it might just be possible. Otherwise you would need a program that just manifests itself as a regular "speaker" and then broadcasts the audio (but then, maybe that is what airsonos does), but then what would the delay be.

My feeling is that this is a difficult problem and I find it unlikely to be solved in a operating system agnostic way, with small delays. SoCo tends to focus on core Sonos functionality (remember, Sonos doesn't actually offer to broadcast your computer audio to their speakers, at least not last time I checked). As such, I think this is out of scope for SoCo, but I think it still might be fun to have discussion about how to solve it here.

Also, if all else fails, you can draw a wire to one of the speakers and use Sonos internal functionality to stream to share with other speakers ;) but I'm unsure of what the delay is for using the generic group functionality is and of course, _copper_ is so last millennium.

**Comment by KennethNielsen** [comment]
And as always. If you do find a way to broadcast you audio as a stream, SoCo can help you play it ;)

**Comment by DeveloperACE** [comment]
yeah. I've tried such broadcast apps but the delay there is pretty significant.

since the only Sonos in my room is a PLAY:1 the only port I have is an ethernet port so yeah, basically what I was wondering was is there a way to use said ethernet port like an AUX cord without messing with the SONOS's internal code/firmware.etc (basically use the ethernet cord as an AUX cord)

**Comment by KennethNielsen** [comment]
@DeveloperACE 

Oh my. The Play1 doesn't have a jack plug, forgot about that. I fairly certain there is no way to use the ethernet cord essentially **as** an AUX. Something like this can be done, but only for broadcasting something over ethernet, so in that case you would convert back whatever the signal was in the first place (like e.g. you can broadcast a screen signal via ethernet, but it is converted at both ends, so in that case you will need the jack plug anyway.

Regarding a brakcast app. Like a said earlier, I think you best bet is to somehow tap directly into the sound system of your machine, since I would expect that for broadcast apps, the delay may be, because the API's they use to interact with the sound system are too slow or becuase they were not internally developed for low delay (like e.g. if you just want to use them for music). But these are just guesses, but that would be what I would be looking for if I was you. Remember, that Sonos can play several standard form of streams, so you do not need something Sonos specific, just look for a low delay way to stream/broadcast your system sound.

**Comment by KennethNielsen** [comment]
Will close this for now. @DeveloperACE feel free to re-open if you wish more discussion.

**Comment by DeveloperACE** [comment]
@KennethNielsen I'm trying to revisit this and see if I can get it working and have had some success with Nicecast but theres still a fairly large delay of a few seconds. Most of the streaming apps I have come across offer internet streaming when all I really need is something that will broadcast to the Sonos over ethernet. GAH

**Comment by DeveloperACE** [comment]
SoCo doesn't happen to have a feature where it plays a stream of audio data does it?

**Comment by DeveloperACE** [comment]
Turns out https://github.com/philippe44/AirConnect works really pretty well with minimal delays. (I guess AirSonos is unmaintained as of right now)

My original intent to be able to use this for watching youtube videos doesn't seem like it will work as there isn't really a totally latency-free way of doing it without the inevitable dropped packets of a Wi-Fi connection and I was unable to figure out how to get it to work over ethernet. Maybe next time.


Thanks for your responses!

**Comment by ghcs27** [comment]
For fixing the latency problem with YouTube videos, you can just delay the video by the same time as the audio. You can either
a) use VLC media player and [this recipe](https://wiki.videolan.org/VLC_HowTo/Adjust_audio_delay/)
b) install a browser addon ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/youtube-audio-sync-tool/) / [Chrome](https://chrome.google.com/webstore/detail/youtube-audio-sync-tool/nhhggkimondhokphkoefldocnnjlimni))
Hope this helps.
