### ISSUE TITLE
Make event handler more relaxed

### ISSUE THREAD

**Issue by maru-sama** [SoCo/SoCo#536]
As mentioned in #467 make the event handler configurable so it handles event messages which are out of specification. Instead of raising an exception it should be possible to either set it to ignore or relaxed.

ignore .... Ignore non conformant events
relaxed ... Try to get as much information out of the xml and forward this with a "broken" flag.

**Comment by KennethNielsen** [comment]
I think this is a good idea and I think this would be good for someone that wants to try their hand at SoCo development, so I'll try to write up some ideas for an implementation and offer to tutor someone that wants to try it:

So, the idea is to make sure that we don't get exceptions in the event parsing, if some music service sends invalid DIDL Lite information (DIDL Lite is the data specification used to communicate metadata for music service items, e.g. tracks and albums).

We will implement this along the lines suggested by @maru-sama, but will change the definitions a little so:

  default ... try out best to parse the event, event if it contains non compliant XML, but fail with exceptions if we don't succeed (current behaviour)
  relaxed ... as above, but instead of failing on non-compliant DidlLite, store the failure data for the failure, along with the failure in a InvalidDidlLite object and return that as the event value (which can easily be checked for in code that responds to events)

I would suggest an implementation along these lines.

 1. First we need to be able to configure which event failure scheme to use, and it should default to "relaxed". Unless someone has a use case for configuring this on an subscription basis, I would suggest to just use a global variable, that would then apply to all subscriptions. E.g. something like `EVENT_POLICY = "relaxed". Remember a proper `data` Sphinx docstring for it.
 2. Implement a InvalidDidlLite class in events.py, which just takes two arguments and stores them, the didl string and the traceback produced when trying to parse it
 3. In `parse_event_xml` find the lines where `from_didl_string` is called, and wrap that in a broad try-except (remember to turn the pylint warning of). In case an exception is raised by the call to `from_didl_string`, save the didl string (the value argument in those lines and a nicely formatted text traceback in a InvalidDidlLite object and assign that to the value variable (where the DidlObject would have been stored, if it succeeded).
 4. Log the failure at the warning level, including both the didl string and the traceback
 5. (Optional, but highly recommended) Capture a LastChanged event string with valid DidlLite and edit it to make sure that it raises an exception in `from_didl_string`. Put both the valid and the invalid version into the `test_event` module and write new tests for `parse_event_xml` that checks that the valid one produces a DidlLite object as value and the invalid one produces the InvalidDidlLite object if EVENT_POLICY is set to relaxed and produces a real exception if not.
 6. Update the docstring for `parse_event_xml` to reflect this new possible value for `value`.

Let me know if you want to give it a shot and feel free to ask questions.

**Comment by maru-sama** [comment]
Closing this old issue now.
