### ISSUE TITLE
Pull request 455 breaks event object for Soundcloud

### ISSUE THREAD

**Issue by maru-sama** [SoCo/SoCo#552]
With the new event handling functionality merged I updated my sonoscontroller to use the new version. Apparently this pull request changes the data returned in an avevent. I have the following code

`
metadata = event.current_track_meta_data 
metadata.album_art_uri
`
After the pull request the event is now returning a MSTrack instead of a DidlMusicTrack for metadata which only seems to contain the title. Is this intentional and should the MSTrack object contain the all the relevant information or is this a bug? Spotify on the other hand still returns a DidlMusicTrack.

**Comment by maru-sama** [comment]
Ok, so apparently this is intentional. I had a closer look at it and attempt_data_structure update in data_structures_entry.py updates the item if it comes from it music service, for the moment it seems to only update the title attribute of the metadata and that's why album_art_uri is empty.

**Comment by ghcs27** [comment]
Seems like the music service data structures need a lot of work.
I'd help out, but unfortunately I don't have any music service accounts, so I can't test it.

**Comment by maru-sama** [comment]
SoundCloud is free of charge so you could use it for testing.

**Comment by ghcs27** [comment]
Thanks for the tip!

**Comment by DPH** [comment]
Hi,
I am happy to test on Spotify, Napster or Amazon
Cheers David

**Comment by maru-sama** [comment]
Hmm, I have a brute force fix although I do not know if this will break other stuff
in data_structures_entry.py:131 where the metadata is passed to the cls, I replaced metadata with didl_item.__dict__. This should add all allowed metadata to the MSTrack object.
On the other hand the initial code went to great lenghts to specify the passed metadata so this might not be correct at all.

**Comment by relevitt** [comment]
In soco.data_structures_entry.py, I have had to comment out the following line in the definition of from_didl_string:

line 53:             #item = attempt_datastructure_upgrade(item)

In my case, this line broke information for items from the "7Digital" musicservice. For me, there seems to be no downside in commenting out this line. Commenting out the line simply fixes what was broken.

As far as I can tell (with limited research), this line has caused bugs for a number of different soco users, with a variety of different use cases.

I haven't attempted to dig into the reasons why this line was added to the code (nor the related attempt_datastructure_upgrade function) nor where this is all going. But I am mystified why something that seemed to be working quite well before this change was broken by making a change which is half  baked and hasn't benefited from adequate (any?) testing.

The attempt_datastructure_upgrade function has the following comment:

        # Ignore other metadata for now, in future ask ms data
        # structure to upgrade metadata from the service

Where is this being done? For example, is there anything in the get_queue() function in soco.core that causes this metadata to be retrieved? 

If this message strikes a note of irritation, that is partly because I spent several days creating improvements for the soco.events module, which IMO are well tested and well thought out, but which have been left out of the soco codebase for reasons I don't understand (not least because they haven't been explained to me in terms I could understand), despite there being a demand for those changes. Meanwhile, half-baked, untested changes which break things are being included.

**Comment by ghcs27** [comment]
Just for reference: PR is at #559

**Comment by KennethNielsen** [comment]
@ghcs27 The music service data structures should actually be in pretty good shape. What we need are reliable music services (see explanation below), which Sonos makes more and more difficult.

@relevitt I realize that we should probably have a blog or something to try and outline some of the direction of the project and such, but here goes. The reason for adding separate data structures for music services is that they are in fact very different beasts. The music structures uses the Didl Lite spec whereas the music services uses another specification, as documented in the module. The point of the change is that those items in the queue should appropriately identify them selves as what ther are, either a DidlLite element from the music library or a MusicServiceItem from a music service.

The point then is. When you query a music service for an item, very little metadata is attached to the search result and no metadat is needed to add it to the queue, since Sonos will get that on the fly. This is kind of practical, because it means that you can get lots of search results, without wasting requests and bandwidth on all the metadata. All the metadata is then supposed to be fetched on the fly and cached on the object once it had been retrieved.

So, the overall plan behind this was, that the music service items, even from the queue, should upon request of the metadata, be able to instantiate the music service it came from and put it in a cache in the ms data structure module, retrieve the metadata on request and cache that on the on the object.

All was going fine until we lost access to all the music services due to the Sonos authentication changes.

Now, you might ask. Why was the upgrade of these items added before we had the rest implemented. The truth is, that at the time there was some focus on bringing the queue elements into a form where they could be re-added to the queue and I'm afraid that the loss of metadata was missed.

Now, looking at the number of issues, this should have been fixed earlier, but the truth is that I didn't see that all of these issues were related. In the future, if anyone spots an issue like that, fell free to join the IRC channel and bring it up there.

**Comment by relevitt** [comment]
@KennethNielsen thank you v much for the explanation. If we've lost access to music services for many (all?) of the popular music services, should music services be retained as part of Soco? I can see the point if there's some hope we will one day be able to access the new Sonos API or if Sonos will change its API so access is available to us again. My understanding from other SoCo contributors is that practically speaking the Sonos auth encryption can't be cracked here (maybe some skilled individuals have achieved it privately for themselves, but that's well beyond my capabilities). Experience suggests that once platforms like Sonos move to encrypted authentication, they never move away from it. So, it seems to me that Soco has lost access for good to all music services that use encrypted authentication. As ever, I worry I'm missing something. If we can no longer search these music services through Soco, then surely the only alternative is to search them through their own APIs? But how do you and other Soco users cope with this problem? Is there a solution I'm missing?

**Comment by KennethNielsen** [comment]
This issue should be fixed by #589 which is now merged. If not feel free to reopen.

**Comment by maru-sama** [comment]
Close issue.
