### ISSUE TITLE
Deprecating support for Python 2.7

### ISSUE THREAD

**Issue by stefankoegl** [SoCo/SoCo#591]
Separate issued branched off from [#337](https://github.com/SoCo/SoCo/issues/337#issuecomment-367275787).

Python 2.7 is the last supported 2.x version and requires some campatability code (#337). Python 2.7 will be maintained until 2020 (https://pythonclock.org/). 

This issue is to discuss our plans for supporting 2.7 for SoCo.

**Comment by stefankoegl** [comment]
My suggest would be as follows
 I'd be open to deprecating it now, with the following implications
* deprecate support for 2.7 with the next release
* set a horizon for removing support with the release following the official end of support for 2.7 in 2020
* until then, continue to fix any bugs and maintain existing code and features
* for new features, if additional effort for achieving 2.7-comatability would be too high, support 3.x only (under the condition that no other features are broken)

**Comment by relevitt** [comment]
Please don't do this! Many people use python 2.7 and have no immediate intention of changing. For example, Ubuntu 16.04 LTS (the version I run) uses python 2.7 as its default. There are significant libraries that haven't been ported to python 3.

**Comment by stefankoegl** [comment]
> Many people use python 2.7 and have no immediate intention of changing.

That would not mean that people have to rewrite all of their Python software. It would only mean that you will need Python 3 for running SoCo.

> Ubuntu 16.04 LTS (the version I run) uses python 2.7 as its default. 

The default version is not really relevant. Ubuntu allows you to install multiple Python versions in parallel. In fact you can simply run `apt-get install python3` to install Python 3 in addition to Python 2.

> There are significant libraries that haven't been ported to python 3.

I tend to disagree on that one. https://python3wos.appspot.com/ - I wouldn't call any of those few red entries as significant.

**Comment by KennethNielsen** [comment]
@stefankoegl you beat me on the wall of superpower.

@relevitt note that we aren't actually doing anything yet. But with regards to at least starting the discussion, the time is now. Not only has most (or all) significant projects been ported, but several projects have also now gone Python 3 only, because the want to use the new features and improvements. In the scientific community e.g. the Jupyter project if I remember correctly.

**Comment by relevitt** [comment]
@stefankoegl:

- An entire 2.7 application that imports soco would have to be ported to python 3.3. I think the codebase of my application is bigger than the soco codebase, as it does many other things beside acting as a sonos controller. So it is a problem for me. Perhaps there are others like me. I'm not aware that other libraries I use are planning to drop 2.7 support.

- Twisted is coloured green on the wall of superpower. From the Twisted website: "Most, but not all, of Twisted has been ported, and therefore only a subset of modules are installed under Python 3." Code green doesn't mean full compatibility has been achieved.

- Some libraries may not be on the wall of superpower, but they are still significant if you happen to use them. For example, I use xmms2 as the media player on my devices, partly because it supports many formats (e.g. flac), partly because it offers a wide choice of APIs for controlling it, including a python API. However, I believe there is little (if any) active development of xmms2 (which is fine for me, because it has never failed me).

**Comment by KennethNielsen** [comment]
@relevitt all those are valid concerns, which is why the transition to Python 3 has taken as long as it has (also because the Python powers-at-be jumped the gun a little) and believe me, I have no desire to try and force people into something that they don't want to.

**BUT!**. This **will** happen at some point anyway. Committing to Python 2 compatibility forever is quite simply too restrictive. Maintaining the 2-3 compatible code makes the task if maintenance and development more difficult, a lot less fun and we cut of selves of from any Python 3-only features.

So. Each of the issues will need to be dealt with at some point anyway. Why not start in good time before everything shuts down.

 * For your code base, to start to port it and see how difficult it is.
 * For twisted, to see whether you use any of the problematic parts
 * For xmms2, to see whether you will need to port that yourself also or move to another library*

I know this part can seem harsh, but really, it isn't fair to make us responsible for other peoples unmaintained code either.

**Comment by relevitt** [comment]
@stefankoegl @KennethNielsen I did the following with my application:

- `print sys.modules.keys()` after everything had been imported
- sorted results into a modules.txt file and deleted local imports, _xxx and __xxx imports
- `caniusepython3 -r modules.txt`

After a mug of coffee, many warnings and several errors, I got this:

You need 16 projects to transition to Python 3.
Of those 16 projects, 15 have no direct dependencies blocking their transition:

  calendar
  ctypes
  email
  enum
  functools
  hashlib
  hmac
  importlib
  logging
  ndg
  pygtk
  definitions (which is blocking sets)
  token
  txws
  xmmsclient

Any advice for me?

**Comment by ghcs27** [comment]
The modules calendar to logging as well as token are from the standard library and available on python 3.
This still leaves:

ndg
pygtk
definitions (blocking sets)
txws
xmmsclient

**Comment by stefankoegl** [comment]
@relevitt, the way forward can only be to convince the maintainers of these packages to support Python 3, and *not* to convince everyone to stay on Python 2.

[ndg](https://pypi.python.org/pypi/ndg) had its last release in 2013, and seems to be unmaintained. If that's the case, you'll need to replace it anyway.
pygtk - see https://askubuntu.com/a/97107
[definitions](https://pypi.python.org/pypi/definitions) seems to be a very small library, which can - on first glance - easily be ported to python3
[txws](https://pypi.python.org/pypi/txWS) last release in 2014, maybe unmaintained?
[xmmsclient](https://pypi.python.org/pypi/xmmsclient) last release in 2012, probably unmaintained

**Comment by ghcs27** [comment]
- Regarding ndg: If you are using [ndg-httpsclient](https://pypi.python.org/pypi/ndg-httpsclient): There is a python 3 compatible version.
- Regarding sets and definitions: The set and frozenset types are builtins now ([stackoverflow](https://stackoverflow.com/questions/12028204/python-cant-import-set-from-sets-no-module-named-sets)). If you don't use definitions directly, then that's solved too.

**Comment by stefankoegl** [comment]
Also I'd like to add that wer're not talking about immediate removal of Python 2.7 support. My suggested timeline would remove support only in 2020.

**Comment by KennethNielsen** [comment]
@relevitt @stefankoegl @ghcs27 might I suggest moving this to a different issue. I don't mind helping out with it and I think it is ok to have this discussion in a SoCo issue, but I would prefer to keep this issue for just the Python 2.7 deprecation issue.

EDIT. Moved to #595 @relevitt please fill in with relevant details there.

**Comment by KennethNielsen** [comment]
@robwebset how are things in the Kodi world these days? (Note for others; @robwebset maintains a plugin for Kodi and Kodi's support of newer Python versions has also historically been slow to progress)

**Comment by KennethNielsen** [comment]
With regards to the procedure, I would like to move faster, but I also want to get feedback from library users.

# Deprecate now, maintain until users that report in are done porting (or Python end-of-life at the latest) except for new functionality

* deprecate support for 2.7 with the next release
* collect and keep track of porting issues of users and plan to remove support entirely when they are done, or when 2.7 reaches official end-of-life in 2020
* until then, continue to fix any bugs and maintain existing code and features
* for new features, if additional effort for achieving 2.7-comatability would be too high, support 3.x only (under the condition that no other features are broken)

**Comment by robwebset** [comment]
Hi @KennethNielsen The Sonos Kodi addon is currently using 0.13 with a patch for #539 - so should be 100% python 2.7 compatible now - I haven't had any reports of this version causing any issues, so I think all is good.
Thanks, Rob

**Comment by robwebset** [comment]
@KennethNielsen I believe there are also plans for Kodi to support python 3 soon(ish) but I don't know how reliable that is, but I believe they were hoping for v18 of Kodi to support it.

**Comment by KennethNielsen** [comment]
@robwebset ok, I guess what I was asking about was more the issues we had with Python 2.6, If I remember it correctly, Kodi has different supported version on different platforms, of which one of them had gotten stuck on Python 2.6. So I guess the questions is, if at some point in the future, you want to move to a newer SoCo, does Kodi support Python 3 all over. Can you comment on the time-line of v18 and whether you expect the Python 3 support to materialize?

**Comment by robwebset** [comment]
@KennethNielsen The current Sonos Addon (v100.2.2) will require Kodi version v17 (as that is the version with Python 2.7 support), users on earlier Kodi versions (with Python 2.6 Support) will use the Sonos Addon (v100.2.1) and wil not be able to update the addon until they adopt the v17 Kodi.

No idea of the v18 time line, as things stand there is no Python 3 support at all, but they are hoping to switch to Python 3 when v18 is released (but no ETA is available for that)

**Comment by KennethNielsen** [comment]
An update from Guido. Python 2.7 EOL is januar 1., 2020.
https://mail.python.org/pipermail/python-dev/2018-March/152348.html

>

**Comment by stefankoegl** [comment]
The [pythonclock.org](https://pythonclock.org/) shows 2 months and 9 days. I think it's time to deprecate support for Python 2.7 also in SoCo.

Any objections?

**Comment by KennethNielsen** [comment]
@stefankoegl not from me, I have been wanting to do that for a while. But I also know that it is a sensitive subject for many, so I wanted if we should push it one more release and in this one insert a warning in `__init__.py`, just to make sure to cross all the t's and dot all the i's.

**Comment by rytilahti** [comment]
I asked on #python@freenode about this related to another project a day back, and the answer I got is that recent-ish pypi versions should do the right thing as long as `python_requires` is set. That is, trying to pip install with pip2, the latest py2 supported version would be installed. But as I have no python2 available (nor a nice test-case for it), I haven't tested myself though...

That being said, it's probably a good idea to add a (deprecation) warning to warn users that there'll be no updates :-)

**Comment by KennethNielsen** [comment]
I made #697 to add the deprecation warning and I will merge it shortly if there are no wild objections.

**Comment by pwt** [comment]
As far as I can tell, Python 2 deprecation in SoCo is now complete, and Python 2 itself has been EOL for over a year, so I'm going to close this issue ahead of the impending v0.21 release.

**Comment by KennethNielsen** [comment]
I think that is fine. Maybe the reason that it wasn't already, was to have some where to keep track of the clean-up/python3 only process of the code. But I think that should probably just be different PR's the then mood moves someone to do it.

**Comment by pwt** [comment]
We've already _de facto_ removed Python 2 support, since we haven't run any 2.x check jobs recently.

FYI, although v0.21 will install on Python 2.7, it hits issues on import:

```
(soco-python2-test) pwt@ubuntu-vm:~$ python
Python 2.7.18 (default, Jan  8 2021, 21:33:07) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pwt/.pyenv/versions/2.7.18/envs/soco-python2-test/lib/python2.7/site-packages/soco/__init__.py", line 16, in <module>
    from .core import SoCo
  File "/home/pwt/.pyenv/versions/2.7.18/envs/soco-python2-test/lib/python2.7/site-packages/soco/core.py", line 274
    raise ValueError("Not a valid IP address string") from error
                                                         ^
SyntaxError: invalid syntax
>>> 
```
It's possible that it's only the new re-raise syntax that breaks compatibility, but I wouldn't bet on it.
