### ISSUE TITLE
Help porting ??? to Python 3

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#595]
This issue is branched of from #591 and started with this message from @relevitt 

> @stefankoegl @KennethNielsen I did the following with my application:
> 
>  *   print sys.modules.keys() after everything had been imported
>  *   sorted results into a modules.txt file and deleted local imports, _xxx and __xxx imports
>  *   caniusepython3 -r modules.txt
> 
> After a mug of coffee, many warnings and several errors, I got this:
> 
> You need 16 projects to transition to Python 3.
> Of those 16 projects, 15 have no direct dependencies blocking their transition:
> 
> calendar
> ctypes
> email
> enum
> functools
> hashlib
> hmac
> importlib
> logging
> ndg
> pygtk
> definitions (which is blocking sets)
> token
> txws
> xmmsclient
> 
> Any advice for me?

followed up by these messages:

@ghcs27 
> The modules calendar to logging as well as token are from the standard library and available on python 3.
> This still leaves:
> 
> ndg
> pygtk
> definitions (blocking sets)
> txws
> xmmsclient

@stefankoegl 
> 
> @relevitt, the way forward can only be to convince the maintainers of these packages to support Python 3, and not to convince everyone to stay on Python 2.
> 
> ndg had its last release in 2013, and seems to be unmaintained. If that's the case, you'll need to replace it anyway.
> pygtk - deprecated, see https://askubuntu.com/a/97107
> definitions seems to be a very small library, which can - on first glance - easily be ported to python3
> txws last release in 2014, maybe unmaintained?
> xmmsclient last release in 2012, probably unmaintained
> 
> It seems to me, regardless of the python 2/3 transition, that your code is relying on packages that are no longer maintained, and will need to be replaced anyway.

@ghcs27 
> * Regarding ndg: If you are using ndg-httpsclient: There is a python 3 compatible version.
> * Regarding sets and definitions: The set and frozenset types are builtins now (stackoverflow). If you don't use definitions directly, then that's solved too.

**Comment by KennethNielsen** [comment]
For xmmsclient https://github.com/randomshinichi/xmmsclient might do the job. Maybe he could be convinced to do a release on PyPI.

**Comment by KennethNielsen** [comment]
With regards to PyGTK (which is Python 2 only), besides from the thread linked to already, there originally was he problem, that GNOME went with a new binding effort called gi.repository, which included Python 3 support but originally no Windows support. That however seems to be coming together: https://stackoverflow.com/questions/12981137/gi-repository-windows

**Comment by relevitt** [comment]
@KennethNielsen @stefankoegl @ghcs27 Thank you for your tips and suggestions. 

I was already running soco modules in separate subprocesses with communication between those subprocesses and my main app being handled by a TCP/IP line receiver. Other potentially blocking processes are also handled in this way. It turned out to be reasonably trivial to port these subprocesses to python 3.

I started the attempt of porting the whole app to python 3, but after completing the syntactical changes, it proved impossible (or impracticable) to deal with the imports. Xmms2 proved the first stumbling block and it was insurmountable. I briefly considered replacing xmms2 with something else (possible choices are vlc and mpd), but neither seems a perfect fit and that's before checking in detail whether they would offer all the basics I'd like to have. There would then be the long task of integrating with my app.

So my main app continues to run on python 2.7, but that doesn't prevent it from communicating via a TCP/IP line receiver with subprocesses running on python 3 that import from soco. So far, objects pickled in python 2 seem to work in python 3 and vice versa, subject to a few teething problems.

At some point, unless the xmms2 devel branch produces updates the stable branch with a python 3 module, I may have to ditch xmms2. An interim stage would be to port the whole of my app, except for a 2.7 subprocess which handles xmms2.

**Comment by KennethNielsen** [comment]
@relevitt what about the unofficial Python 3 port of xmms I linked to. If that works, and the license is liberal enough, you might just include it in your codebase, to get around it not being release on PyPI.

**Comment by relevitt** [comment]
@KennethNielsen I installed the unofficial Python 3 port of xmmsclient, but the attempt to import it under python 3 failed.

Normally, I'd try to get to the bottom of the problem and try to fix it, but most of the xmmsclient code consists of .c files supplying C bindings. To install the module, you need to compile the .c files. This in turn requires you have the correct C headers and development libraries - i.e. you need to install the xmms development files.

The first time I tried that, the build failed, presumably because I'd installed the stable branch (via apt install), whereas the unofficial Python 3 port is based off the development branch (query, which version of the development branch).

When I'd installed the development branch of xmms (via git clone), the build and install succeeded, but the resulting module failed to import. At that point, I gave up!

**Comment by KennethNielsen** [comment]
@relevitt understandable. It would of course also be preferred that the original project would make an effort to port to Python 3. You can always make an issue. That can't hurt.

On a side note. Regarding pickle and serialization. Adding serialization methods to various SoCo data structure would be very acceptable. We just decided not to add them until someone asked for it.

**Comment by KennethNielsen** [comment]
I guess this is closed for now then. Re-open if you wish further help to push forward.
