### ISSUE TITLE
discover for multiple household_id's

### ISSUE THREAD

**Issue by twosky2000** [SoCo/SoCo#624]
We have 2 sonos houshold_id's in our hous, so that my parents don't see my speakers and miss click play functions in my setup with high volume settings.

When I discover on my network i only get one houshold_id worth of devices 2/4. Is this a feature that is doable in SoCo or are there more problems after adding support for multiple housholds?

Here is the static IP's

LAN | 192.168.0.151 | 5c:aa:fd:45:##:## Sonos, Inc. | SonosZP_Kitchen | Sonos Kitchen | online | static
-- | -- | -- | -- | -- | -- | --
LAN | 192.168.0.152 | 94:9f:3e:74:##:## Sonos, Inc. | SonosZP_Mobile | Sonos Mobile | online | static
LAN | 192.168.0.156 | 00:0e:58:56:##:## Sonos, Inc. | SonosZP_Tobi | Sonos Tobi | online | static
LAN | 192.168.0.157 | 00:0e:58:73:##:## Sonos, Inc. | SonosZP_Bad | Sonos Bad | online | static

Example discover output:
> python3 commandline/discover.py 
> Tobi
> Bad

**Comment by DPH** [comment]
Hi @twosky2000,
looking at the soco.discover it looks like once it finds one zone player it uses that player to give details of all (every player knows about the other players - in that household!)
This was done to speed it up rather than wait for discovery to return each device.
Therefore whichever player is discovered first it will show all players in that household group.

With current code I don't see how you can choose which household to discover. I believe an option could be added to discover to specify the household_id you want and then discover would wait for the first discovery with that household_id. This would be pretty easy to implement.

Is that what you are looking for?
Do others think this approach would work and makes sense?

Cheers David

**Comment by twosky2000** [comment]
Hi @DPH,
yes that what it seams to me. Great code comments!
Just wanted to ask if there will be a problem or nobody had the need yet. I have to tinker around sometime, cause i don't understand python classes to well.

**Comment by twosky2000** [comment]
from [discover.py](https://github.com/SoCo/SoCo/blob/master/soco/discovery.py#L181)
`181                    zone = config.SOCO_CLASS(addr[0])`
SoCo gets the list of devices from the sonos device. So it can never get devices that have diffrent household_id's. I don't see it as a feature of soco, so i will try to get it working on home assistant without using discover.

Cheers and thanks

**Comment by twosky2000** [comment]
I made a pr with a quick&dirty patch to discovery. Works fine for my home and passes lint. But there are other changes breaking CI. Any suggestions welcome.

**Comment by pwt** [comment]
This is addressed now. Please see https://github.com/SoCo/SoCo/pull/644#issuecomment-738042748.
