### ISSUE TITLE
Discovery not reporting any speaker on Windows

### ISSUE THREAD

**Issue by gilou** [SoCo/SoCo#625]
Hi,
I just tried soco 0.15 on Python 3.7.0 on Windows 10, and discovery() doesn't yield anything.
```
>>> import soco
>>> soco.discover()
>>> s = soco.SoCo("xxx.xxx.xxx.xxx")
>>> s
SoCo("xxx.xxx.xxx.xxx")
>>> s.get_speaker_info()
{'player_icon': '/img/icon-ZP90.png', 'mac_address': ... }

```
I tried also with the interface_addr to no avail. Firewall lets all necessary multicast go through (the sonos controller sees the devices). The network is configured as a /16, and the computer is on the same layer2 segment as the SoCos connect devices.
On Linux, soco 0.15, Python 3.5.2 it works fine. I don't have a lot more platforms to test on, but might if it's interesting (I guess Windows isn't the default choice for most of you ;))

**Comment by ghcs27** [comment]
> I tried also with the interface_addr to no avail.

Hmm, I would have suggested this as the first step, but it seems like you already tried it out. Which addresses did you use?

**Comment by gilou** [comment]
Hi, I used the IP in the same subnet as the Sonos devices, I don't have it at hand... I also fully disabled the Windows firewall, and could do the discovery from Linux while connected on the same switch as the Windows PC...
@DPH I don't have an easy access to that network, but I can try on Python 3.6 at some point to see if it could be a regression on Python 3.7 or just a glitch on that setup..

**Comment by pwt** [comment]
I have a similar issue. I have two Sonos installations, in different locations.

In **one** of these locations, SoCo discovery works if a machine has a wired Ethernet interface, but does not work if there's only a wireless interface (the multicast request times out without a response). Identical behaviour on both macOS and Windows. No such problem in the other location, with a different model of router.

Any ideas? I'm running with SoCo 0.19, Python 3.7.

**Comment by KennethNielsen** [comment]
@gilou I'm curious whether the problem still exists for you? Also, you said you tried the interface_addr approach. Did you try that in combination with the netifaces approach as mentioned in the docstring (https://github.com/SoCo/SoCo/blob/master/soco/discovery.py#L53) to make sure that the right ip adresses were tried?

@pwt could you try the netifaces trick as well?

**Comment by pwt** [comment]
@KennethNielsen Yes -- tried that without success. I'm pretty certain that in my case this is a router multicast issue, so it makes me wonder whether other reports of this issue have the same (or similar) cause.

The only curiosity is that the Sonos controller app works fine on the same WiFi network; maybe it has some fallback alternative when multicast doesn't work.

**Comment by KennethNielsen** [comment]
@pwt ok. Yeah. I have been suspecting router issues as well, but I also agree that obviously since the official controller works there must be a way around it. A could of things comes to mind:

1) First of, since I know that you already know how to capture Wireshark traces, I was wondering whether I could persuade you to capture a trace during startup of the official app on the "problematic" network?
2) Obviously it cannot be what the official app does, but I was wondering whether, as a stop gap measure if we could simple cache ip adresses for zones that we "saw" or connected to recently. Discovery only needs to know about one zone to find the rest, since as soon as it discovers on, it asks that for the topology.
3) A third option, maybe combined with 2, could be to simple brute force the problem. If nothing is found, simple try all addresses on the subnet in threads. This is of course probably considered "offensive" network behavior, but if we hide it behind a switch I don't see a problem with it.

**Comment by pwt** [comment]
@KennethNielsen Good ideas. I'll run a WS capture on the Sonos app. when I'm next at the property with the problematic router.

**Comment by gilou** [comment]
Hi,
I don’t have access to that setup anymore, but it it’s somehow related to multicast, that might have been the culprit. I can’t help until I get a new Sonos device...

**Comment by KennethNielsen** [comment]
@gilou ok, thanks for reporting it in the first place

**Comment by pwt** [comment]
Discovery has been thoroughly updated in [SoCo 0.21](https://github.com/SoCo/SoCo/issues/747), with all the common stumbling blocks addressed, as well as adding support for multiple Sonos systems on the same network. SoCo 0.21 will be released on or before 17-Jan-2021.

This issue is stale now, so I'll close it.
