### ISSUE TITLE
Account discovery NOT working ANYMORE

### ISSUE THREAD

**Issue by ProjectGhostCore** [SoCo/SoCo#627]
Hi,

since Sonos removed the http:xxx:1400/status/accounts interface it's no longer possible to discover the connected music service accounts this way! (soco.music_services.accounts.Account)

How can you get them now ??

**Comment by ProjectGhostCore** [comment]
push

**Comment by ghcs27** [comment]
It seems like Sonos has totally removed the possibility of getting music service accounts for third party clients - see the meta issue #557. (AFAIK, it's because they worry about the security of account credentials.)
I know this is a huge issue, but apparently we can't do much about it at the moment. Any updates for the problem will be posted to #557.
