### ISSUE TITLE
Struggling to make soco.discover() work with Python 3.

### ISSUE THREAD

**Issue by kimaldis** [SoCo/SoCo#636]
The code snippet below runs just fine using python 2.7 but fails when using python 3. Any thoughts appreciated.

```
import soco
print(  soco.discover() )
```
error: 
```
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    print(  soco.discover() )
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/soco/discovery.py", line 131, in discover
    _sock.sendto(really_utf8(PLAYER_SEARCH), (MCAST_GRP, MCAST_PORT))
OSError: [Errno 64] Host is down
```

**Comment by rytilahti** [comment]
FWIW, this seems to be an OSX problem (works fine with python 3.6.5 on linux).

**Comment by schinckel** [comment]
It works for me on macOS (Python 3.7.2)

**Comment by KennethNielsen** [comment]
Hi @kimaldis 

I don't think this is a Python 3 issue, more likely something to do with setup. System Python on MacOS is notorious, so an extra bi-sectioning could be, if the Python 3 is a MacOS system Python, then try and install a stand alone one e.g. with the anaconda distribution or a virtual env or similar.

I may also be some rules in the OS about which programs are allowed to do what. A quick search revealed e.g. this: https://aminsblog.wordpress.com/2012/05/12/mac-os-x-host-is-down-with-curl-python-pipetc/

Finally, we do have some problems with discovery on "exotic" network setups proxies etc., but since it does work for you in Python 2.7 I wouldn't suspect that.

**Comment by pwt** [comment]
Closed due to inactivity.
