### ISSUE TITLE
Future Warning

### ISSUE THREAD

**Issue by matthewfelgate** [SoCo/SoCo#648]
```
/Library/Python/2.7/site-packages/soco/services.py:687: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  value_list_elt = state.find('{}allowedValueList'.format(ns))\
```

**Comment by ghcs27** [comment]
The line in question:
```python
value_list_elt = state.find('{}allowedValueList'.format(ns)) or ()
```
We use it to handle the case if the function returns None. Internally, what the `or` does is
```python
elt = state.find('{}allowedValueList'.format(ns))
if bool(elt) == True:
    value_list_elt = elt
else:
    value_list_elt = ()
```
The variable `elt` is an XML element or None, and the warning means that the output of `bool(elt)` might change, possibly to handle empty elements differently. However, our only requirements are that (1) bool(elt) is false if elt is None, so we don't get a TypeError, and (2) bool(elt) is true if it contains items, so we can iterate over it. Since this is not going to change, we can just ignore the warning.

**Comment by matthewfelgate** [comment]
Thanks

**Comment by pwt** [comment]
Closed due to inactivity (and probably no longer relevant).
