### ISSUE TITLE
avTransport events duplicated 

### ISSUE THREAD

**Issue by CheapB** [SoCo/SoCo#718]
When going from stopped to play on a radio station TRANSITIONING and PLAYING are fired twice. When going from PAUSED_PLAYBACK to PLAYING TRANSITIONING is fired twice. going from one play list to another seems to fire one TRANSITIONING and one PLAYING. Is this intentional?

`	sonos = soco.SoCo(<insert ip address>).group.coordinator
	sub = sonos.avTransport.subscribe(auto_renew=True)

	while True:
		try:
			event = sub.events.get(timeout=0.5)
			print(event)
			print(event.sid)
			print(event.seq)        
			print (event.variables)

		except Empty : 
			pass
		except KeyboardInterrupt:
			sub.unsubscribe()
			event_listener.stop()
			break`

**Comment by KennethNielsen** [comment]
Hi @CheapB 

Thanks for the report. Unless due to some bug, we just relay the events that the Sonos speakers broadcasts, to keep the amount of magic in SoCo to a minumum. What this means, I'm afraid, is that handling duplicates will have to be handled at the application level. So you have to allow your application to handle receiving the same event twice in a row.
