### ISSUE TITLE
Confusion about missing features from the Control API

### ISSUE THREAD

**Issue by JessicaTegner** [SoCo/SoCo#908]
Hi there.
Amazing library first of all.
I was looking for a way to get tts notifications through my sonos products and many suggested this libraries, with various methods to do it.
I looked through the [Sonos Control API](https://developer.sonos.com/reference/control-api/) and saw they have something called AudioClip.
Which got me thinking. It seems like this library is missing oauth support, audioclip and basically anything else that runs through sonos servers.
Is this planned, or haven't I just not found it in this library yet.

If not. I would be happy to start on a library, complementing this, but with all the stuff from the Control API, that touches sonos servers.

Please advice :)

**Comment by jjlawren** [comment]
That specific API isn't necessary to use for TTS announcements. You can use this library to play back audio files generated from TTS services using the `SoCo.play_uri()`, for example. It also has support for creating snapshots of speaker groups & states so you can restore after playing the announcement.

As of now `SoCo` only works with the local UPnP API, not the cloud-based ones. If you're looking for something that uses the `audioClip` cloud API specifically, I wrote something that works Home Assistant here: https://github.com/jjlawren/sonos_cloud. Using that would support TTS out of the box, but you can also use it as a reference if you're looking to build something yourself.

**Comment by NicklasTegner** [comment]
@jjlawren  nice. I rolled my own, since it didn't seem like the Sonos cloud apis was supported with SoCo.
I really feel like storing and restoring snapshots, are way too messy compared to the audioclip api, for instance..

So yeah. Was just wondering if the Sonos cloud api/ oauth would be supported here, or if I should start work on a cloud specific sonos library for python (that could complement this one)

**Comment by jjlawren** [comment]
> I really feel like storing and restoring snapshots, are way too messy compared to the audioclip api, for instance..

Yep, that's why made the project I linked above. The user experience with `audioClip` is very nice for short alerts & notifications.

> So yeah. Was just wondering if the Sonos cloud api/ oauth would be supported here, or if I should start work on a cloud specific sonos library for python (that could complement this one)

There is some oauth and cloud API support in `SoCo` today with the new music services overhaul. It's needed to create/maintain auth to each music provider (e.g., Spotify, Amazon, Apple, etc) and interact with each provider's music service API. However I think long-term it would make sense to offload oauth to an existing maintained library instead of using a custom implementation.

**Comment by pwt** [comment]
> So yeah. Was just wondering if the Sonos cloud api/ oauth would be supported here, or if I should start work on a cloud specific sonos library for python (that could complement this one)

It would be a good complement. Please drop us a pointer to it when you have something you'd like to share.

Right now the local UPnP API has much more functionality than the Sonos cloud API, it's much faster, and it doesn't require app auth. However, I'd expect the cloud API to improve over time.

**Comment by NicklasTegner** [comment]
I will show it on here, when I've made something worth noting.
I'm marking this as resolved.
Thanks for the answers guys :)

**Comment by NicklasTegner** [comment]
@pwt  and others interested.
I have started work on a complementary package here: https://github.com/nicklastegner/sonos-web-apis

Right now there's the oauth api working, next is the audio clip api.
I'm working towards an 1.0.0 milestone.

Preliminary documentation can be found on https://sonos-web-apis.readthedocs.io/en/latest/

**Comment by pwt** [comment]
Thanks for the pointer, @JessicaTegner.
